"""Joke and fun fact of the day for the kids' pages. Each kid gets a different one each day."""
from datetime import date

JOKES = [
    ("Why did the math book look sad?", "It had too many problems."),
    ("What do you call a bear with no teeth?", "A gummy bear!"),
    ("Why can't a bicycle stand up by itself?", "It's two tired."),
    ("What do you call a fish with no eyes?", "A fsh."),
    ("Why did the cookie go to the doctor?", "It felt crummy."),
    ("What has hands but can't clap?", "A clock."),
    ("Why don't eggs tell jokes?", "They'd crack each other up."),
    ("What do you call a sleeping dinosaur?", "A dino-snore!"),
    ("Why did the student eat his homework?", "The teacher said it was a piece of cake."),
    ("What falls in winter but never gets hurt?", "Snow!"),
    ("Why are ghosts bad at lying?", "You can see right through them."),
    ("What do you call a pig that does karate?", "A pork chop."),
    ("How do you make a tissue dance?", "Put a little boogie in it."),
    ("Why did the banana go to the doctor?", "It wasn't peeling well."),
    ("What kind of tree fits in your hand?", "A palm tree!"),
    ("Why was the broom late?", "It over-swept."),
    ("What do you call a cow with no legs?", "Ground beef."),
    ("What goes up but never comes down?", "Your age."),
    ("Why did the golfer bring two pairs of pants?", "In case he got a hole in one."),
    ("What do you call a dog magician?", "A labracadabrador."),
    ("Why do fish live in salt water?", "Because pepper makes them sneeze!"),
    ("What did the ocean say to the beach?", "Nothing, it just waved."),
    ("How does a penguin build its house?", "Igloos it together."),
    ("What's a cat's favourite colour?", "Purr-ple."),
    ("Why did the scarecrow win an award?", "He was outstanding in his field."),
    ("What do you call a train carrying bubblegum?", "A chew-chew train."),
    ("What do elves learn in school?", "The elf-abet."),
    ("Why did the teddy bear skip dessert?", "It was already stuffed."),
    ("What did one plate say to the other?", "Lunch is on me!"),
    ("Why can't Elsa have a balloon?", "Because she'll let it go."),
    ("What do you call a lazy kangaroo?", "A pouch potato."),
    ("What did the left eye say to the right eye?", "Between you and me, something smells."),
    ("Why did the computer go to the doctor?", "It had a virus."),
    ("What kind of music do mummies like?", "Wrap music."),
    ("Why are frogs so happy?", "They eat whatever bugs them."),
    ("What do you call a snowman in summer?", "A puddle."),
    ("How do you catch a squirrel?", "Climb a tree and act like a nut."),
    ("What do you call a bee that can't make up its mind?", "A maybe!"),
    ("Why did the robot go on vacation?", "It needed to recharge its batteries."),
    ("What has four wheels and flies?", "A garbage truck."),
    ("Why did the owl invite friends over?", "It didn't want to be owl by itself."),
    ("What do you call a shoe made of a banana?", "A slipper."),
]

FACTS = [
    "Octopuses have three hearts and blue blood. 🐙",
    "A group of flamingos is called a flamboyance. 🦩",
    "Honey never goes bad. Honey found in ancient tombs was still good to eat! 🍯",
    "Sea otters hold hands while they sleep so they don't float away. 🦦",
    "A day on Venus is longer than a whole year on Venus. 🪐",
    "Bananas are berries, but strawberries aren't! 🍌",
    "Newfoundland dogs have webbed feet, which makes them great swimmers. 🐕",
    "Your heart beats about 100,000 times every day. ❤️",
    "Puffins can carry more than 10 fish in their beak at once! 🐧",
    "Sharks were around before trees existed. 🦈",
    "A snail can sleep for three years. 🐌",
    "Butterflies taste with their feet. 🦋",
    "The Moon is slowly moving away from Earth, about 4 cm every year. 🌙",
    "Cows have best friends and get stressed when they're apart. 🐄",
    "Some icebergs are made of snow that fell over 10,000 years ago. 🧊",
    "A bolt of lightning is about five times hotter than the surface of the Sun. ⚡",
    "Koalas sleep up to 22 hours a day. 🐨",
    "There are more stars in space than grains of sand on all of Earth's beaches. ✨",
    "A blue whale's heart is about the size of a small car. 🐋",
    "Hummingbirds can fly backwards. 🐦",
    "The Eiffel Tower gets about 15 cm taller in summer because metal grows when it's hot. 🗼",
    "Sloths can hold their breath longer than dolphins can. 🦥",
    "Your nose can remember about 50,000 different smells. 👃",
    "Rabbits can't throw up. 🐇",
    "Some turtles can breathe through their bottoms! 🐢",
    "An ostrich's eye is bigger than its brain. 🦤",
    "The first video game was made in 1958. 🎮",
    "Humpback whales sing songs that can last for hours! 🐳",
    "A cloud can weigh more than a million kilograms. ☁️",
    "Dolphins give each other names using special whistles. 🐬",
    "Cats spend about two thirds of their lives asleep. 🐈",
    "Jupiter is so big that all the other planets could fit inside it. 🪐",
    "Frogs drink water through their skin. 🐸",
    "Hawaii is the only U.S. state where coffee grows. 🌺",
    "Starfish don't have brains. ⭐",
    "The tongue of a blue whale weighs as much as an elephant. 🐘",
    "Mushrooms are more closely related to animals than to plants. 🍄",
    "Penguins propose with a pebble. 🐧",
    "Your bones are about five times stronger than steel of the same weight. 🦴",
    "Some pineapples take two years to grow. 🍍",
    "Coins used to be made of real silver. 🪙",
    "Mario's first game was in 1981, and he was called Jumpman! ⭐",
]


def for_kid(kid_id: int, day: date) -> dict:
    n = day.toordinal()
    q, a = JOKES[(n * 2 + kid_id * 13) % len(JOKES)]
    return {"joke": q, "punchline": a, "fact": FACTS[(n * 3 + kid_id * 29) % len(FACTS)]}
